### PR TITLE
Set pybind11 to ValeevGroup/v2.11

### PR DESCRIPTION
**Pull request by asadchev**

### CODE REVIEW

**Comment by evaleev** [comment]
for some reason py3.12 is picked up again in https://github.com/evaleev/libint/actions/runs/6987480217/job/19014069994?pr=283#step:14:153 .. I thought https://github.com/evaleev/libint/pull/280 addressed this by pinning to 3.11 MacOS CI jobs ..

**Comment by asadchev** [comment]
I think easiest is for me to fix it.
Is there MAC i can use?

**Comment by evaleev** [comment]
> I think easiest is for me to fix it. Is there MAC i can use?
> […](#)

I think this is not related to MacOS, but due to the use of py3.12 ... try running pylibint tests built w/ py3.12 on Linux

**Comment by evaleev** [comment]
I see master has macOS python tests disabled per #280, you reenabled them in https://github.com/evaleev/libint/pull/283/commits/77c26cc8f003e418cf6cef83c5d395324e89f624 ... the issue is pylibint w/ py3.12 does not seem to work (recall the GIL check failure)

**Comment by loriab** [comment]
Is it the intent that only the ValeevGroup fork of pb11 (and never a generic upstream release) is suitable for pylibint? If so, perhaps `find_package(pybind11 2.6.0 CONFIG)` should be commented out.

**Comment by evaleev** [comment]
> Is it the intent that only the ValeevGroup fork of pb11 (and never a generic upstream release) is suitable for pylibint? If so, perhaps `find_package(pybind11 2.6.0 CONFIG)` should be commented out.

there is only 1 extra file we need on top of stock pb11 (https://github.com/pybind/pybind11/commit/42b42ce0071413ba63fbc056f0316a85adbfefc4), for handling `boost::container::small_vector` ... unfortunately we can'd PR upstream since it's too specialized. We need this across the board (e.g. in https://github.com/ValeevGroup/tiledarray). Unfortunately there is no good way to reuse a single file across multiple packages without creating the extra boilerplate to maintain. We are considering submodules. We manually prepare releases, so the inability of GitHub to package submodules source into releases (https://github.com/dear-github/dear-github/issues/214) does not affect libint.

Comments are welcome.

**Comment by asadchev** [comment]
Re Python 3.12
It's only been two months since 3.12 release and there are changes re GIL.
Pybind11 probably hasn't caught up with all bugs that may exist.  We
shouldnt try to support 3.12.  Python interpreter can be set explicitly via
CMake to be not 3.12

**Comment by evaleev** [comment]
@asadchev btw, relevant: looks like `pybind11` can use targets provided by `FindPython` if it's loaded before `pybynd11`: https://pybind11.readthedocs.io/en/stable/cmake/index.html#new-findpython-mode

**Pull request merged**
